// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
//import "dotenv/config";
//config({ path: ".env.local" });
import { defineConfig } from "prisma/config";
import { PrismaNeon } from "@prisma/adapter-neon";
import * as dotenv from "dotenv";

dotenv.config({ path: ".env.local" });
export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
  // @ts-expect-error - migrate is early access
  migrate: {
    async adapter() {
      return new PrismaNeon({ connectionString: process.env.DATABASE_URL });
    },
  },
});
